package wormz.fatweaks.ASM;

import net.minecraft.launchwrapper.IClassTransformer;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.*;

import static org.objectweb.asm.Opcodes.*;

public class IETransformer implements IClassTransformer {
    @Override
    public byte[] transform(String name, String transformedName, byte[] bytes) {
        if (name.equals("ferro2000.immersivetech.common.blocks.metal.tileentities.TileEntityAlternator")) {
            ClassReader cr = new ClassReader(bytes);
            ClassNode cn = new ClassNode();
            cr.accept(cn, 0);
            for (MethodNode mn : cn.methods) {
                if (mn.name.equals("func_73660_a")) {
                    mn.instructions.clear();
                    mn.visitCode();
                    Label l0 = new Label();
                    mn.visitLabel(l0);
                    mn.visitLineNumber(49, l0);
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitFieldInsn(GETFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "field_145850_b", "Lnet/minecraft/world/World;");
                    mn.visitFieldInsn(GETFIELD, "net/minecraft/world/World", "field_72995_K", "Z");
                    Label l1 = new Label();
                    mn.visitJumpInsn(IFNE, l1);
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitFieldInsn(GETFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "formed", "Z");
                    mn.visitJumpInsn(IFEQ, l1);
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitFieldInsn(GETFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "field_174879_c", "I");
                    mn.visitIntInsn(BIPUSH, 13);
                    mn.visitJumpInsn(IF_ICMPNE, l1);
                    Label l2 = new Label();
                    mn.visitLabel(l2);
                    mn.visitLineNumber(51, l2);
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitFieldInsn(GETFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "field_145850_b", "Lnet/minecraft/world/World;");
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitMethodInsn(INVOKEVIRTUAL, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "func_174877_v", "()Lnet/minecraft/util/math/BlockPos;", false);
                    mn.visitMethodInsn(INVOKESTATIC, "ferro2000/immersivetech/api/ITUtils", "checkMechanicalEnergyTransmitter", "(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)Z", false);
                    Label l3 = new Label();
                    mn.visitJumpInsn(IFEQ, l3);
                    Label l4 = new Label();
                    mn.visitLabel(l4);
                    mn.visitLineNumber(53, l4);
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitFieldInsn(GETFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "field_145850_b", "Lnet/minecraft/world/World;");
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitMethodInsn(INVOKEVIRTUAL, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "func_174877_v", "()Lnet/minecraft/util/math/BlockPos;", false);
                    mn.visitMethodInsn(INVOKESTATIC, "ferro2000/immersivetech/api/ITUtils", "getMechanicalEnergy", "(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)Lferro2000/immersivetech/api/energy/MechanicalEnergy;", false);
                    mn.visitFieldInsn(PUTFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "mechanicalEnergy", "Lferro2000/immersivetech/api/energy/MechanicalEnergy;");
                    mn.visitLabel(l3);
                    mn.visitLineNumber(57, l3);
                    mn.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitFieldInsn(GETFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "mechanicalEnergy", "Lferro2000/immersivetech/api/energy/MechanicalEnergy;");
                    mn.visitMethodInsn(INVOKEVIRTUAL, "ferro2000/immersivetech/api/energy/MechanicalEnergy", "getEnergy", "()I", false);
                    Label l5 = new Label();
                    mn.visitJumpInsn(IFLE, l5);
                    Label l6 = new Label();
                    mn.visitLabel(l6);
                    mn.visitLineNumber(58, l6);
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitFieldInsn(GETFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "energyStorage", "Lblusunrize/immersiveengineering/api/energy/immersiveflux/FluxStorage;");
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitFieldInsn(GETFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "mechanicalEnergy", "Lferro2000/immersivetech/api/energy/MechanicalEnergy;");
                    mn.visitMethodInsn(INVOKEVIRTUAL, "ferro2000/immersivetech/api/energy/MechanicalEnergy", "getEnergy", "()I", false);
                    mn.visitFieldInsn(GETSTATIC, "ferro2000/immersivetech/common/Config$ITConfig$Machines", "alternator_RfModifier", "I");
                    mn.visitInsn(IDIV);
                    mn.visitMethodInsn(INVOKEVIRTUAL, "blusunrize/immersiveengineering/api/energy/immersiveflux/FluxStorage", "modifyEnergyStored", "(I)V", false);
                    mn.visitLabel(l5);
                    mn.visitLineNumber(61, l5);
                    mn.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitFieldInsn(GETFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "energyStorage", "Lblusunrize/immersiveengineering/api/energy/immersiveflux/FluxStorage;");
                    mn.visitMethodInsn(INVOKEVIRTUAL, "blusunrize/immersiveengineering/api/energy/immersiveflux/FluxStorage", "getEnergyStored", "()I", false);
                    mn.visitJumpInsn(IFLE, l1);
                    Label l7 = new Label();
                    mn.visitLabel(l7);
                    mn.visitLineNumber(65, l7);
                    mn.visitInsn(ICONST_0);
                    mn.visitVarInsn(ISTORE, 3);
                    Label l8 = new Label();
                    mn.visitLabel(l8);
                    mn.visitLineNumber(67, l8);
                    mn.visitInsn(ICONST_0);
                    mn.visitVarInsn(ISTORE, 4);
                    Label l9 = new Label();
                    mn.visitLabel(l9);
                    mn.visitFrame(Opcodes.F_FULL, 5, new Object[] {"ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", Opcodes.TOP, Opcodes.TOP, Opcodes.INTEGER, Opcodes.INTEGER}, 0, new Object[] {});
                    mn.visitVarInsn(ILOAD, 4);
                    mn.visitIntInsn(BIPUSH, 6);
                    mn.visitJumpInsn(IF_ICMPGE, l1);
                    Label l10 = new Label();
                    mn.visitLabel(l10);
                    mn.visitLineNumber(69, l10);
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitFieldInsn(GETFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "facing", "Lnet/minecraft/util/EnumFacing;");
                    mn.visitVarInsn(ASTORE, 2);
                    Label l11 = new Label();
                    mn.visitLabel(l11);
                    mn.visitLineNumber(71, l11);
                    mn.visitVarInsn(ILOAD, 4);
                    mn.visitInsn(ICONST_3);
                    Label l12 = new Label();
                    mn.visitJumpInsn(IF_ICMPGE, l12);
                    Label l13 = new Label();
                    mn.visitLabel(l13);
                    mn.visitLineNumber(73, l13);
                    mn.visitVarInsn(ALOAD, 2);
                    mn.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/EnumFacing", "func_176735_f", "()Lnet/minecraft/util/EnumFacing;", false);
                    mn.visitVarInsn(ASTORE, 2);
                    Label l14 = new Label();
                    mn.visitLabel(l14);
                    mn.visitLineNumber(74, l14);
                    mn.visitVarInsn(ILOAD, 4);
                    mn.visitInsn(ICONST_1);
                    mn.visitInsn(ISUB);
                    mn.visitVarInsn(ISTORE, 3);
                    Label l15 = new Label();
                    mn.visitJumpInsn(GOTO, l15);
                    mn.visitLabel(l12);
                    mn.visitLineNumber(78, l12);
                    mn.visitFrame(Opcodes.F_FULL, 5, new Object[] {"ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", Opcodes.TOP, "net/minecraft/util/EnumFacing", Opcodes.INTEGER, Opcodes.INTEGER}, 0, new Object[] {});
                    mn.visitVarInsn(ALOAD, 2);
                    mn.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/EnumFacing", "func_176746_e", "()Lnet/minecraft/util/EnumFacing;", false);
                    mn.visitVarInsn(ASTORE, 2);
                    Label l16 = new Label();
                    mn.visitLabel(l16);
                    mn.visitLineNumber(79, l16);
                    mn.visitVarInsn(ILOAD, 4);
                    mn.visitInsn(ICONST_4);
                    mn.visitInsn(ISUB);
                    mn.visitVarInsn(ISTORE, 3);
                    mn.visitLabel(l15);
                    mn.visitLineNumber(83, l15);
                    mn.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitFieldInsn(GETFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "field_145850_b", "Lnet/minecraft/world/World;");
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitMethodInsn(INVOKEVIRTUAL, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "func_174877_v", "()Lnet/minecraft/util/math/BlockPos;", false);
                    mn.visitInsn(ICONST_0);
                    mn.visitVarInsn(ILOAD, 3);
                    mn.visitInsn(ICONST_0);
                    mn.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/BlockPos", "func_177982_a", "(III)Lnet/minecraft/util/math/BlockPos;", false);
                    mn.visitVarInsn(ALOAD, 2);
                    mn.visitInsn(ICONST_2);
                    mn.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/math/BlockPos", "func_177967_a", "(Lnet/minecraft/util/EnumFacing;I)Lnet/minecraft/util/math/BlockPos;", false);
                    mn.visitMethodInsn(INVOKESTATIC, "blusunrize/immersiveengineering/common/util/Utils", "getExistingTileEntity", "(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/tileentity/TileEntity;", false);
                    mn.visitVarInsn(ASTORE, 1);
                    Label l17 = new Label();
                    mn.visitLabel(l17);
                    mn.visitLineNumber(84, l17);
                    mn.visitVarInsn(ALOAD, 2);
                    mn.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/util/EnumFacing", "func_176734_d", "()Lnet/minecraft/util/EnumFacing;", false);
                    mn.visitVarInsn(ASTORE, 5);
                    Label l18 = new Label();
                    mn.visitLabel(l18);
                    mn.visitLineNumber(86, l18);
                    mn.visitVarInsn(ALOAD, 1);
                    mn.visitVarInsn(ALOAD, 5);
                    mn.visitMethodInsn(INVOKESTATIC, "blusunrize/immersiveengineering/common/util/EnergyHelper", "isFluxReceiver", "(Lnet/minecraft/tileentity/TileEntity;Lnet/minecraft/util/EnumFacing;)Z", false);
                    Label l19 = new Label();
                    mn.visitJumpInsn(IFEQ, l19);
                    Label l20 = new Label();
                    mn.visitLabel(l20);
                    mn.visitLineNumber(88, l20);
                    mn.visitFieldInsn(GETSTATIC, "ferro2000/immersivetech/common/Config$ITConfig$Machines", "alternator_RfPerTick", "I");
                    mn.visitVarInsn(ISTORE, 6);
                    Label l21 = new Label();
                    mn.visitLabel(l21);
                    mn.visitLineNumber(90, l21);
                    mn.visitVarInsn(ALOAD, 1);
                    mn.visitVarInsn(ALOAD, 5);
                    mn.visitVarInsn(ILOAD, 6);
                    mn.visitInsn(ICONST_1);
                    mn.visitMethodInsn(INVOKESTATIC, "blusunrize/immersiveengineering/common/util/EnergyHelper", "insertFlux", "(Lnet/minecraft/tileentity/TileEntity;Lnet/minecraft/util/EnumFacing;IZ)I", false);
                    mn.visitJumpInsn(IFLE, l19);
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitFieldInsn(GETFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "energyStorage", "Lblusunrize/immersiveengineering/api/energy/immersiveflux/FluxStorage;");
                    mn.visitMethodInsn(INVOKEVIRTUAL, "blusunrize/immersiveengineering/api/energy/immersiveflux/FluxStorage", "getEnergyStored", "()I", false);
                    mn.visitVarInsn(ILOAD, 6);
                    mn.visitJumpInsn(IF_ICMPLE, l19);
                    Label l22 = new Label();
                    mn.visitLabel(l22);
                    mn.visitLineNumber(92, l22);
                    mn.visitVarInsn(ALOAD, 1);
                    mn.visitVarInsn(ALOAD, 5);
                    mn.visitVarInsn(ILOAD, 6);
                    mn.visitInsn(ICONST_0);
                    mn.visitMethodInsn(INVOKESTATIC, "blusunrize/immersiveengineering/common/util/EnergyHelper", "insertFlux", "(Lnet/minecraft/tileentity/TileEntity;Lnet/minecraft/util/EnumFacing;IZ)I", false);
                    mn.visitInsn(POP);
                    Label l23 = new Label();
                    mn.visitLabel(l23);
                    mn.visitLineNumber(93, l23);
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitFieldInsn(GETFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "energyStorage", "Lblusunrize/immersiveengineering/api/energy/immersiveflux/FluxStorage;");
                    mn.visitVarInsn(ALOAD, 0);
                    mn.visitFieldInsn(GETFIELD, "ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "energyStorage", "Lblusunrize/immersiveengineering/api/energy/immersiveflux/FluxStorage;");
                    mn.visitMethodInsn(INVOKEVIRTUAL, "blusunrize/immersiveengineering/api/energy/immersiveflux/FluxStorage", "getEnergyStored", "()I", false);
                    mn.visitVarInsn(ILOAD, 6);
                    mn.visitInsn(ISUB);
                    mn.visitMethodInsn(INVOKEVIRTUAL, "blusunrize/immersiveengineering/api/energy/immersiveflux/FluxStorage", "setEnergy", "(I)V", false);
                    mn.visitLabel(l19);
                    mn.visitLineNumber(67, l19);
                    mn.visitFrame(Opcodes.F_FULL, 5, new Object[] {"ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator", "net/minecraft/tileentity/TileEntity", "net/minecraft/util/EnumFacing", Opcodes.INTEGER, Opcodes.INTEGER}, 0, new Object[] {});
                    mn.visitIincInsn(4, 1);
                    mn.visitJumpInsn(GOTO, l9);
                    mn.visitLabel(l1);
                    mn.visitLineNumber(105, l1);
                    mn.visitFrame(Opcodes.F_FULL, 1, new Object[] {"ferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator"}, 0, new Object[] {});
                    mn.visitInsn(RETURN);
                    Label l24 = new Label();
                    mn.visitLabel(l24);
                    mn.visitLocalVariable("output", "I", null, l21, l19, 6);
                    mn.visitLocalVariable("energyFacing", "Lnet/minecraft/util/EnumFacing;", null, l18, l19, 5);
                    mn.visitLocalVariable("tileEntity", "Lnet/minecraft/tileentity/TileEntity;", null, l17, l1, 1);
                    mn.visitLocalVariable("f", "Lnet/minecraft/util/EnumFacing;", null, l11, l1, 2);
                    mn.visitLocalVariable("i", "I", null, l9, l1, 4);
                    mn.visitLocalVariable("h", "I", null, l8, l1, 3);
                    mn.visitLocalVariable("this", "Lferro2000/immersivetech/common/blocks/metal/tileentities/TileEntityAlternator;", null, l0, l24, 0);
                    mn.visitMaxs(5, 7);
                    mn.visitEnd();
                }
            }
            ClassWriter cw = new ClassWriter(0);
            cn.accept(cw);
            return cw.toByteArray();
        } else {
            return bytes;
        }
    }
}
